name: MLlabs
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - jupyter
  - folium
  - geopandas
  - matplotlib
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - shapely
  - pytorch

